name: flutter_generative_ai_app_ask_dash
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  api_client:
    path: packages/api_client
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.2
  equatable: ^2.0.5
  flame: ^1.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  path_drawing: ^1.0.1
  phased: ^0.0.3
  questions_repository:
    path: packages/questions_repository
  url_launcher: ^6.2.2


  cupertino_icons: ^1.0.2

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.7
  url_launcher_platform_interface: ^2.2.0
  very_good_analysis: ^5.1.0

dependency_overrides:
  flame:
    git:
      url: https://github.com/flame-engine/flame.git
      path: packages/flame
      ref: main

flutter_gen:
  line_length: 80 #


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
    - assets/rating-assets/


